repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings==1.7.0',
            'flake8-bugbear==24.2.6',
            'flake8-comprehensions==3.14.0',
            'flake8-import-order==0.18.2'
        ] 